# Site settings
title: Thrive Pattern Library
email: melissa.keizer@theappbuilder.com
description: > # this means to ignore newlines until "baseurl:"
 Thrives's centralised hub for showcasing our design rules, principles, and frontend components.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patterns.thrive.app" # the base hostname & protocol for your site, e.g. http://example.com

# For Github pages site
# baseurl /thrivepatterns
# url https://melissakeizer.github.io
# For local development keep these blank


twitter_username: theappbuilder
github_username:  theappbuilder
website_url:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
